[package]
name = "ssh-fetch-keys"
version = "0.1.0"
authors = ["Scott C Wang <wangsc@cs.wisc.edu>"]
edition = "2018"

[dependencies]
users = "0.11"
regex = "1.5"
curl = "0.4"
crc = "2.0"
anyhow = "1.0"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.5"
clap = "2.33"